name: Build with dependencies from conda
on: [push]
jobs:
  build-with-conda:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Cache miniconda packages
        uses: actions/cache@v2
        env:
          cache-name: cache-miniconda
        with:
          path: ~/miniconda3
          key: ${{ runner.os }}-${{ env.cache-name }}-v1-${{ hashFiles('setup/conda_env_setup.bash', 'setup/conda_env_setup_${{ runner.os }}.bash') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-
      - name: Install miniconda
        run: |
          conda config --set auto_activate_base false  # try to avoid upstream's conda interfering
          if [[ ! -e ~/miniconda3 ]]; then
            curl -OL https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
            bash Miniconda3-latest-Linux-x86_64.sh -b
          fi
      - name: (re-)Create build environment
        run: |
          source ~/miniconda3/etc/profile.d/conda.sh
          conda env remove -n build || true
          conda create -y -n build
          conda config --add channels conda-forge
          conda config --set channel_priority strict
      - name: Run conda env setup
        run: |
          source ~/miniconda3/etc/profile.d/conda.sh
          conda activate build
          bash -x setup/conda_env_setup_${{ runner.os }}.bash
      # - name: Examine pkg-config
      #   run: |
      #     source ~/miniconda3/etc/profile.d/conda.sh
      #     conda activate build
      - name: Build and install
        run: |
          source ~/miniconda3/etc/profile.d/conda.sh
          conda activate build
          make install PREFIX=$CONDA_PREFIX NEED_CUDA=no
